version: "3.9"
services:
  node:
    container_name: nodejs
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dbg
    ports:
      - "3000:3000"
      - "9229:9229"
    security_opt:
      - "seccomp:unconfined"
    command:
      - node
      - "--inspect-brk=0.0.0.0"
      - "app.js"
